Repository tutur3u/platform, pull requests merged in 2024-10, with the labels that each got.

#1838 Improve file upload
  apps/rewise/src/components/chat-panel.tsx
  apps/rewise/src/components/prompt-form.tsx
  apps/rewise/src/utils/supabase/client.ts
  apps/rewise/src/utils/supabase/server.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/chat/chat.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/row-actions.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/finance/transactions/[transactionId]/bill.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/finance/transactions/[transactionId]/page.tsx
  apps/web/src/app/api/workspaces/[wsId]/upload/route.ts
  apps/web/src/components/chat-panel.tsx
  apps/web/src/components/prompt-form.tsx
  apps/web/src/utils/supabase/client.ts
  packages/ui/src/components/ui/custom/file-uploader.tsx
Labels: enhancement, help wanted

#1862 Add remove birthday button
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/database/row-actions.tsx
  apps/web/src/components/row-actions/users/date-picker.tsx
Labels: enhancement

#1876 Add user group schedule display and enhance current navlink calculation logic
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/structure.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/attendance/user-month-attendance.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/groups/[groupId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/groups/[groupId]/posts.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/groups/[groupId]/schedule.tsx
Labels: enhancement

#1887 feat: implement promotion management
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/promotions/columns.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/promotions/form.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/promotions/loading.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/promotions/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/promotions/row-actions.tsx
  apps/web/src/app/api/v1/workspaces/[wsId]/promotions/[promotionId]/route.ts
  apps/web/src/app/api/v1/workspaces/[wsId]/promotions/route.ts
  apps/web/src/lib/workspace-helper.ts
Labels: enhancement

#1894 feat(drive): implement initial folder support and path-context uploads
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/columns.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/form.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/page.tsx
  apps/web/src/types/primitives/StorageObject.ts
Labels: enhancement

#1931 Add Novel Text Editor and allow sharing document pages
  apps/rewise/package.json
  apps/web/package.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/[documentId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/advanced-editor.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/content.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/dialog-content.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/document-share-dialog.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/extensions.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/ai-completion-command.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/ai-selector-commands.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/ai-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/generative-menu-switch.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/image-upload.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/selectors/color-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/selectors/link-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/selectors/math-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/selectors/node-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/selectors/text-buttons.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/slash-command.tsx
  apps/web/src/app/api/v1/workspaces/[wsId]/documents/route.ts
  apps/web/src/components/document/DocumentCard.tsx
  apps/web/src/constants/common.ts
  apps/web/src/types/supabase.ts
  apps/web/supabase/migrations/20241019094032_new_migration.sql
  pnpm-lock.yaml
Labels: enhancement

#1950 Add course objectives and extra reading management
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/[documentId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/advanced-editor.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/extensions.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/ai-selector.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/generative/generative-menu-switch.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/documents/slash-command.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/extra-content/editor.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/extra-content/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/flashcards/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/layout.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/link-button.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/objectives/editor.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/objectives/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/quizzes/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/resources/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/section.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/education/courses/[courseId]/youtube-links/page.tsx
  apps/web/src/types/supabase.ts
Labels: enhancement

#1949 feat(product): implement category create in combobox
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/products/[productId]/form.tsx
Labels: enhancement

#1960 feat(product): enhance warehouse input
  apps/web/src/app/[locale]/(dashboard)/[wsId]/inventory/products/[productId]/form.tsx
Labels: enhancement

#1962 feat(drive): implement dropdown actions and folder create
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/new-actions.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/page.tsx
Labels: enhancement

#1976 fix(drive): map `path` to rename/download/delete actions
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/columns.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/row-actions.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/drive/table.tsx
Labels: bug
