Repository tutur3u/platform, pull requests merged in 2025-10, with the labels that each got.

#3669 Add additional realtime support for task labels, assignees
  apps/docs/mint.json
  packages/ui/src/components/ui/text-editor/editor.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/kanban.tsx
  packages/ui/src/components/ui/tu-do/shared/board-client.tsx
  packages/ui/src/components/ui/tu-do/shared/board-header.tsx
  packages/ui/src/components/ui/tu-do/shared/board-views.tsx
  packages/ui/src/components/ui/tu-do/shared/list-view.tsx
  packages/ui/src/hooks/useBoardRealtime.ts
Labels: enhancement, platform, tudo

#3673 Add Pending Invoices Support
  apps/db/supabase/migrations/20251002093207_pending_invoices.sql
  apps/db/supabase/seed.sql
  apps/finance/messages/en.json
  apps/finance/messages/vi.json
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/(workspace-settings)/migrations/migration-dashboard.tsx
  apps/web/src/app/api/v1/infrastructure/bill-coupons/route.ts
  apps/web/src/app/api/v1/infrastructure/bill-packages/route.ts
  apps/web/src/app/api/v1/infrastructure/bills/route.ts
  apps/web/src/app/api/v1/infrastructure/class-attendance/route.ts
  apps/web/src/app/api/v1/infrastructure/class-members/route.ts
  apps/web/src/app/api/v1/infrastructure/class-packages/route.ts
  apps/web/src/app/api/v1/infrastructure/class-scores/route.ts
  apps/web/src/app/api/v1/infrastructure/classes/route.ts
  apps/web/src/app/api/v1/infrastructure/coupons/route.ts
  apps/web/src/app/api/v1/infrastructure/lessons/route.ts
  apps/web/src/app/api/v1/infrastructure/package-stock-changes/route.ts
  apps/web/src/app/api/v1/infrastructure/packages/route.ts
  apps/web/src/app/api/v1/infrastructure/payment-methods/route.ts
  apps/web/src/app/api/v1/infrastructure/product-categories/route.ts
  apps/web/src/app/api/v1/infrastructure/product-prices/route.ts
  apps/web/src/app/api/v1/infrastructure/product-units/route.ts
  apps/web/src/app/api/v1/infrastructure/roles/route.ts
  apps/web/src/app/api/v1/infrastructure/score-names/route.ts
  apps/web/src/app/api/v1/infrastructure/student-feedbacks/route.ts
  apps/web/src/app/api/v1/infrastructure/transaction-categories/route.ts
  apps/web/src/app/api/v1/infrastructure/user-coupons/route.ts
  apps/web/src/app/api/v1/infrastructure/user-monthly-report-logs/route.ts
  apps/web/src/app/api/v1/infrastructure/user-monthly-reports/route.ts
  apps/web/src/app/api/v1/infrastructure/user-status-changes/route.ts
  apps/web/src/app/api/v1/infrastructure/users/route.ts
  apps/web/src/app/api/v1/infrastructure/wallet-transactions/route.ts
  apps/web/src/app/api/v1/infrastructure/wallets/route.ts
  apps/web/src/app/api/v1/infrastructure/warehouses/route.ts
  packages/types/src/primitives/PendingInvoice.ts
  packages/types/src/primitives/index.ts
  packages/types/src/supabase.ts
  packages/ui/src/components/ui/finance/invoices/hooks.ts
  packages/ui/src/components/ui/finance/invoices/invoice-page.tsx
  packages/ui/src/components/ui/finance/invoices/new-invoice-page.tsx
  packages/ui/src/components/ui/finance/invoices/pending-columns.tsx
  packages/ui/src/components/ui/finance/invoices/pending-invoices-table.tsx
  packages/ui/src/components/ui/finance/invoices/subscription-invoice.tsx
Labels: enhancement, platform

#3696 Add user status presence in task dialog and disable realtime feature for personal workspace
  apps/rewise/src/hooks/use-presence.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/tasks/projects/[projectId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/tasks/projects/[projectId]/task-project-detail.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/task.tsx
  packages/ui/src/components/ui/tu-do/shared/board-client.tsx
  packages/ui/src/components/ui/tu-do/shared/board-header.tsx
  packages/ui/src/components/ui/tu-do/shared/board-views.tsx
  packages/ui/src/components/ui/tu-do/shared/list-view.tsx
  packages/ui/src/components/ui/tu-do/shared/task-edit-dialog.tsx
  packages/ui/src/components/ui/tu-do/shared/user-presence-avatars.tsx
  packages/ui/src/hooks/useBoardRealtime.ts
  packages/ui/src/hooks/usePresence.ts
Labels: enhancement, platform, tudo

#3700 Refactor task components
  apps/web/src/components/image-cropper.tsx
  bun.lock
  packages/ui/package.json
  packages/ui/src/components/ui/text-editor/editor.tsx
  packages/ui/src/components/ui/text-editor/extensions.ts
  packages/ui/src/components/ui/text-editor/mention-extension.tsx
  packages/ui/src/components/ui/text-editor/tool-bar.tsx
  packages/ui/src/components/ui/text-editor/video-extension.ts
  packages/ui/src/components/ui/tu-do/boards/boardId/hooks/__tests__/use-task-actions.test.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/hooks/use-task-actions.ts
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/__tests__/task-menus.test.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/index.ts
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-due-date-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-estimation-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-labels-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-move-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-priority-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/menus/task-projects-menu.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/task.tsx
  packages/ui/src/components/ui/tu-do/shared/custom-date-picker/custom-date-picker-dialog.tsx
  packages/ui/src/components/ui/tu-do/shared/mention-system/__tests__/mention-system.test.ts
  packages/ui/src/components/ui/tu-do/shared/mention-system/mention-menu.tsx
  packages/ui/src/components/ui/tu-do/shared/mention-system/types.ts
  packages/ui/src/components/ui/tu-do/shared/mention-system/use-mention-suggestions.ts
  packages/ui/src/components/ui/tu-do/shared/slash-commands/__tests__/slash-commands.test.ts
  packages/ui/src/components/ui/tu-do/shared/slash-commands/definitions.ts
  packages/ui/src/components/ui/tu-do/shared/slash-commands/slash-command-menu.tsx
  packages/ui/src/components/ui/tu-do/shared/task-edit-dialog.tsx
  packages/ui/vitest.config.ts
  packages/ui/vitest.setup.ts
Labels: enhancement, platform, tudo

#3706 Refactor custom hook files
  apps/nova/src/components/custom-data-table.tsx
  apps/nova/src/hooks/use-confetti.ts
  apps/nova/src/hooks/useSearchParams.tsx
  apps/nova/src/lib/hooks/use-copy-to-clipboard.tsx
  apps/rewise/src/components/chat-message-actions.tsx
  apps/rewise/src/components/chat-scroll-anchor.tsx
  apps/rewise/src/components/custom-data-table.tsx
  apps/rewise/src/components/custom-month-picker.tsx
  apps/rewise/src/components/prompt-form.tsx
  apps/rewise/src/components/scroll-to-bottom-button.tsx
  apps/rewise/src/components/scroll-to-top-button.tsx
  apps/rewise/src/hooks/use-messages.ts
  apps/rewise/src/hooks/useDeepgram.tsx
  apps/rewise/src/hooks/useSearchParams.tsx
  apps/rewise/src/lib/hooks/use-at-bottom.tsx
  apps/rewise/src/lib/hooks/use-copy-to-clipboard.tsx
  apps/rewise/src/lib/hooks/use-enter-submit.tsx
  apps/rewise/src/lib/hooks/use-local-storage.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/(dashboard)/finance-toggle.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/(workspace-settings)/members/_components/tab-navigation.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/ai/spark/hooks/usePlanTasks.ts
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/attendance/client-user-attendances.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/attendance/user-month-attendance-skeleton.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/attendance/user-month-attendance.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/groups/[groupId]/attendance/client.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/groups/[groupId]/schedule.tsx
  apps/web/src/components/chat-message-actions.tsx
  apps/web/src/components/chat-scroll-anchor.tsx
  apps/web/src/components/custom-month-picker.tsx
  apps/web/src/components/general-search-bar.tsx
  apps/web/src/components/prompt-form.tsx
  apps/web/src/components/scroll-to-bottom-button.tsx
  apps/web/src/components/scroll-to-top-button.tsx
  apps/web/src/hooks/useSearchParams.tsx
  apps/web/src/hooks/useSidebar.tsx
  apps/web/src/lib/hooks/use-at-bottom.tsx
  apps/web/src/lib/hooks/use-copy-to-clipboard.tsx
  apps/web/src/lib/hooks/use-enter-submit.tsx
  apps/web/src/lib/hooks/use-local-storage.ts
  packages/ui/package.json
  packages/ui/src/hooks/scheduled-events-utils.tsx
  packages/ui/src/hooks/use-at-bottom.tsx
  packages/ui/src/hooks/use-copy-to-clipboard.ts
  packages/ui/src/hooks/use-enter-submit.tsx
  packages/ui/src/hooks/use-local-storage.ts
Labels: enhancement, platform

#3710 View Sent Emails by Users
  apps/db/supabase/migrations/20251007120500_fix_check_guest_lead_generation_conditions.sql
  apps/web/messages/en.json
  apps/web/messages/vi.json
  apps/web/package.json
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/[userId]/follow-up/client.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/[userId]/follow-up/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/attendance/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/database/[userId]/page.tsx
  apps/web/src/app/[locale]/(dashboard)/[wsId]/users/database/[userId]/sent-emails-client.tsx
  bun.lock
  packages/ui/src/components/ui/custom/lead-generation-preview.tsx
Labels: enhancement, platform

#3713 Implement collaborator cursors for Kanban board
  packages/supabase/src/next/realtime.ts
  packages/ui/src/components/ui/tu-do/boards/boardId/kanban.tsx
  packages/ui/src/components/ui/tu-do/shared/collaborator-cursor.tsx
  packages/ui/src/components/ui/tu-do/shared/cursor-overlay.tsx
  packages/ui/src/hooks/useCursorTracking.ts
Labels: enhancement, platform, tudo

#3717 Allow board creation from task popup
  apps/web/src/app/[locale]/(dashboard)/[wsId]/tasks/my-tasks/my-tasks-content.tsx
  packages/ui/src/components/ui/custom/combobox.tsx
  packages/ui/src/components/ui/tu-do/boards/form.tsx
Labels: enhancement, tudo

#3724 Filter tasks by unassigned
  apps/web/src/app/[locale]/(dashboard)/[wsId]/tasks/projects/[projectId]/task-project-detail.tsx
  packages/ui/src/components/ui/tu-do/boards/boardId/task-filter.tsx
  packages/ui/src/components/ui/tu-do/shared/board-views.tsx
Labels: enhancement, tudo
